### PR TITLE
Make sure builds executed locally don't fail

### LINKED ISSUE #77: bazel build //... should be runnable without RBE in order to support PRs from external forks
## Description

bazel build //... should be runnable without RBE in order to support PRs from external forks. Right now it would fail: https://circleci.com/gh/graknlabs/grakn/21383

### PR DESCRIPTION
**Pull request by vmax**
Fixes #77 
The logic is as follows:
- if build is *not* an RBE build:
  - if platform is Linux:
    - `apt-get install rpm`
  - if platform is Darwin:
    - `brew install rpm`
  - else
    - fail

### CODE REVIEW

**Comment by lolski** [comment]
are dependencies like these something that "Bazel toolchain" should solve for us?

**Comment by vmax** [comment]
@lolski I don't think 'bazel toolchain' is responsible for _obtaining_ your tools, only for _locating_ them when they are already present

File: ci/install-bazel-rbe.sh [hunk 1]
```diff
@@ -1,6 +1,20 @@
 #!/bin/bash
 
 set -e
+
+function install_rpmbuild() {
```
Comment (lolski) [inline ci/install-bazel-rbe.sh]: Let's call the function `install_dependencies` instead. Because it reads better from a high level

File: ci/install-bazel-rbe.sh [hunk 2]
```diff
@@ -10,4 +24,5 @@ if [[ -n "$BAZEL_RBE_CREDENTIAL" ]]; then
     echo "The RBE credential has been installed!"
 else
     echo "No RBE credential found. Bazel will be executed locally without RBE support."
+    install_rpmbuild
```
Comment (lolski) [inline ci/install-bazel-rbe.sh]: Let's put the code outside of the if else, so that it is always installed regardless of whether you've RBE.

Is there a better file to host the code? I think `install-bazel-rbe.sh` should only be for installing RBE.

File: ci/install-bazel-rbe.sh (hunk 1 above)
Comment (vmax) [reply ci/install-bazel-rbe.sh]: @lolski fixed in https://github.com/graknlabs/build-tools/pull/78/commits/1c3dc1b28ed7a6c165806bc4d24e1dc493c6ecfa

File: ci/install-bazel-rbe.sh (hunk 2 above)
Comment (vmax) [reply ci/install-bazel-rbe.sh]: @lolski 
>it is always installed regardless of whether you've RBE.

This is redundant — RBE builds do not require `rpmbuild` installed and we'll lose ~15 seconds per each build

>Is there a better file to host the code? I think install-bazel-rbe.sh should only be for installing RBE.

`rpmbuild` is always needed, regardless of platform. In that way, I feel installing `rpmbuild` _only_ in `else` branch, when RBE is not present, is an implementation detail. 

A bigger idea for refactor might be merging install *all* needed deps for build (`bazel`, `rbe credential`, `rpmbuild`) in a script named `install-build-tools`

Comment (lolski) [reply ci/install-bazel-rbe.sh]: > This is redundant — RBE builds do not require rpmbuild installed and we'll lose ~15 seconds per each build

True, however imagine a user running Bazel command without RBE, in a machine which has RBE credential which will cause it to fail. That would be quite a confusing error. I think it's better to be slower for 15 seconds rather than be confusing.

> A bigger idea for refactor might be merging install all needed deps for build (bazel, rbe credential, rpmbuild) in a script named install-build-tools

This sounds like a good idea in the future. Can you create a Github issue for that?

Comment (vmax) [reply ci/install-bazel-rbe.sh]: @lolski addressed in https://github.com/graknlabs/build-tools/pull/78/commits/e80d9ee9c06241a881ac24a8426c8f46a8e24032

Comment (vmax) [reply ci/install-bazel-rbe.sh]: @lolski issue https://github.com/graknlabs/build-tools/issues/79 created
